### ISSUE TITLE
Duplicate results

### ISSUE THREAD

**Issue by camilstaps** [KDercksen/cloogle-cli#10]
E.g.

    python3 cloogle-cli.py -n 50 -m StdList

will produce suplicate results. If I'm not mistaken, this is because in `get_data` you're assuming that `more_available` is always overridden. This is not the case; `more_available` is an optional field. If it is not there, that means there are no more results.

**Comment by camilstaps** [comment]
It actually also looks like the first 15 results are always duplicated, while results from further pages are missing.

**Comment by KDercksen** [comment]
The issue is actually that 'page' was missing from the request payload. 

However, it seems that there is still repetition when there's less than `maxitems` results; output is padded with results until `maxitems` is reached.

**Comment by KDercksen** [comment]
By the way, `more_available` does seem to be always there, with the value `0` when there are no more results.

**Comment by camilstaps** [comment]
Yeah, I just had a quick look at your code. There are requests for which the response does not have the `more_available` field, e.g. `{"name":"","unify":"","modules":[""]}` or when you get the page wrong (`{"name":"","unify":"","page":1000}`).

**Comment by KDercksen** [comment]
Ahh okay, I see. Those are not cases that should realistically happen, but it's good to know!
