### ISSUE TITLE
Suggestion: consider talking to the Clean backend directly

### ISSUE THREAD

**Issue by camilstaps** [KDercksen/cloogle-cli#2]
Since the PHP script is just a wrapper in the new version of Cloogle, you may want to consider talking to the Clean backend directly. It runs a TCP server, typically on port 31215. You can send JSON requests, e.g. `{"name":"isMember","unify":"a [a] -> Bool"}` and receive results in the same manner as the PHP script used to. Connections are closed directly.

The advantage would be less overhead because no HTTP server is needed. There is no one preferred way apart from that.

**Comment by KDercksen** [comment]
Do you think the HTTP overhead is significant enough to justify every user running their own CloogleServer? It is a great idea an sich, and I'm in favour of supporting communication with a local CloogleServer instance, but I'm not sure if it should be the only way to use cloogle-cli. Thoughts?

**Comment by camilstaps** [comment]
Sorry, this is not what I mean. The server in dopefishh/cloogle runs the TCP server. Instead of talking to the HTTP server you can talk to that TCP server directly, if you wish.

cloogle.org doens't use the new version yet, but you can test on cloogle.camilstaps.nl:31215.

**Comment by KDercksen** [comment]
Oh, I see, that makes more sense. Thanks for the clarification! I'll be working on this.

**Comment by KDercksen** [comment]
We now communicate directly through TCP.
